export const services = [
  {
    id: "suit",
    name: "Suit",
    price: 5,
    category: "clothing",
    image: "https://i.imgur.com/6vVf5VZ.png", // AI-generated suit image
  },
  {
    id: "casual_pair",
    name: "Casual Wear (Trouser/Skirt + Shirt/Polo)",
    price: 3,
    category: "clothing",
    image: "https://i.imgur.com/0Zlq3cK.png",
  },
  {
    id: "single_casual",
    name: "Single Casual Item",
    price: 1.5,
    category: "clothing",
    image: "https://i.imgur.com/3B2iI3n.png",
  },
  {
    id: "gown_set",
    name: "Gown / Skirt & Blouse",
    price: 4,
    category: "clothing",
    image: "https://i.imgur.com/LGQHcN1.png",
  },
  {
    id: "bed_cover",
    name: "Bed Cover",
    price: 6,
    category: "bedding",
    image: "https://i.imgur.com/EVlO6X5.png",
  },
  {
    id: "duvet",
    name: "Duvet",
    price: 9,
    category: "bedding",
    image: "https://i.imgur.com/Nt2jI0L.png",
  },
  {
    id: "fan_pack",
    name: "Fan Pack",
    price: 2,
    category: "accessories",
    image: "https://i.imgur.com/dZT2u8l.png",
  },
  {
    id: "laptop_bag",
    name: "Laptop Bag",
    price: 4,
    category: "accessories",
    image: "https://i.imgur.com/BzjFzW5.png",
  },
  {
    id: "sneakers",
    name: "Sneakers",
    price: 3,
    category: "footwear",
    image: "https://i.imgur.com/tPZ2rHi.png",
  },
];